const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_TO_CART = "REMOVE_TO_CART";
const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const TOGGLE_CART = "TOGGLE_CART"

export { ADD_TO_CART, REMOVE_TO_CART, INCREMENT, DECREMENT, TOGGLE_CART};
